# Generated by Django 5.1.3 on 2024-12-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='landmarks',
            field=models.JSONField(default=list),
        ),
    ]
