# Generated by Django 5.1.3 on 2025-02-20 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0002_pose_landmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_keypoints', models.JSONField()),
                ('threshold_flexion', models.FloatField()),
                ('threshold_extension', models.FloatField()),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_type', models.CharField(choices=[('Angle of three points', 'Angle Of Three Points'), ('Velocity of point', 'Velocity Of Point'), ('Acceleration of point', 'Acceleration Of Point'), ('Distance between points', 'Distance Between Points'), ('Angle with horizontal', 'Angle With Horizontal'), ('Angle with vertical', 'Angle With Vertical'), ('Angle with line', 'Angle With Line')], max_length=50)),
                ('keypoints', models.JSONField()),
                ('show_alert_if_above', models.FloatField(blank=True, null=True)),
                ('show_alert_if_below', models.FloatField(blank=True, null=True)),
                ('alert_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poseapp.exercisedetail')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poseapp.routineconfig')),
                ('custom_tracking_details', models.ManyToManyField(blank=True, related_name='routine_exercises', to='poseapp.trackingdetail')),
            ],
        ),
        migrations.AddField(
            model_name='routineconfig',
            name='exercises',
            field=models.ManyToManyField(related_name='routine_configs', through='poseapp.RoutineExercise', to='poseapp.exercisedetail'),
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='default_tracking_details',
            field=models.ManyToManyField(related_name='exercise_details', to='poseapp.trackingdetail'),
        ),
    ]
