# Generated by Django 5.1.3 on 2025-02-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0003_exercisedetail_routineconfig_trackingdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineconfig',
            name='name',
            field=models.CharField(default='Unnamed Routine', max_length=100),
        ),
    ]
