# Generated by Django 5.1.3 on 2025-03-01 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0004_routineconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedetail',
            name='rep_tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poseapp.trackingdetail'),
        ),
        migrations.AddField(
            model_name='trackingdetail',
            name='dimensionality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingdetail',
            name='goal_extension',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdetail',
            name='goal_flexion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
