# Generated by Django 5.1.3 on 2025-03-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0005_exercisedetail_rep_tracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.IntegerField()),
                ('max_flexion', models.FloatField()),
                ('max_extension', models.FloatField()),
                ('concentric_time', models.FloatField()),
                ('eccentric_time', models.FloatField()),
                ('total_time', models.FloatField()),
                ('goal_flexion_met', models.BooleanField()),
                ('goal_extension_met', models.BooleanField()),
                ('score', models.FloatField()),
                ('alerts', models.JSONField(default=list)),
                ('poses', models.ManyToManyField(blank=True, to='poseapp.pose')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineComponentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_data', models.ManyToManyField(to='poseapp.repdata')),
                ('routine_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poseapp.routineexercise')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine_component_data', models.ManyToManyField(to='poseapp.routinecomponentdata')),
                ('routine_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poseapp.routineconfig')),
            ],
        ),
    ]
