# Generated by Django 5.1.3 on 2025-03-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0006_repdata_routinecomponentdata_routinedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedetail',
            name='body_alignment',
            field=models.CharField(default='TODO', max_length=50),
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='instruction',
            field=models.CharField(default='Enter some instructions to show the user...', max_length=900),
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='min_rep_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='start_angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='start_in_flexion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingdetail',
            name='symmetric',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trackingdetail',
            name='dimensionality',
            field=models.CharField(blank=True, default='2D', max_length=50),
        ),
    ]
