# Generated by Django 5.1.3 on 2025-03-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0007_exercisedetail_body_alignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineconfig',
            name='injury',
            field=models.CharField(default='No Injury Specified', max_length=100),
        ),
    ]
