# Generated by Django 5.1.3 on 2025-03-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0009_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
    ]
