# Generated by Django 5.1.3 on 2025-03-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0010_remove_patient_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repdata',
            old_name='score',
            new_name='max_score',
        ),
    ]
