# Generated by Django 5.1.3 on 2025-03-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0011_rename_score_repdata_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinecomponentdata',
            name='routine_component',
        ),
        migrations.AddField(
            model_name='routinecomponentdata',
            name='exercise_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poseapp.exercisedetail'),
        ),
    ]
