# Generated by Django 5.1.3 on 2025-04-14 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0013_patient_user_routinecomponentdata_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
